.eslintrc.js
package.json
src/contexts/AccountUIContext/dispatchActions.ts
src/contexts/AccountUIContext/reducer.ts
src/data/translations/english.ts
src/data/translations/french.ts
yarn.lock

- Add some alternative strings that can be used by the Trans component from i18next-react for formatting string internals
- Add a new Auth action to reset the transit state for login request
- Update lint dependencies

Add some alternative translation strings

---

CHANGELOG.md
docs/API.md
package.json
src/contexts/AuthUIContextProvider/provider.tsx
src/contexts/AuthUIContextProvider/types.ts
src/data/translations/english.ts
src/data/translations/french.ts
src/types/ContactParams.tsx

Adds the latest changes from the Shiverware implementation.
- -   `phoneContactLink` to `AuthUIContextProviderProps` to allow specification of tel URI details while keeping `phoneContact` for human-readable UI display of the same number
- Twek some translation strings

Port latest shiverware changes

---

src/data/translations/english.ts
src/data/translations/french.ts

Fixes https://github.com/pxblue/react-workflows/issues/13.
- Update the wording so it doesn't say "press continue to continue"

Update wording for continue

---

.circleci/config.yml
PUBLISHING.md

Add publish step and docs

---

docs/API.md
package.json
src/contexts/AuthUIContextProvider/types.ts

Fixes # .
- Allow function option for header and footer to give users access to the navigation prop in their custom components.

Allow for function types in header and footer

---

CHANGELOG.md
docs/API.md
package.json
src/contexts/AuthUIContextProvider/types.ts

Fixes PXBLUE-2024.
- Update registrationSuccessScreen type definition

Update registrationSuccessScreen type definition

---

src/data/translations/chinese.ts
src/data/translations/i18n.ts
src/data/translations/index.ts
src/index.ts

- Adds Chinese translations (thanks @huayunh)

Add some Chinese translations

---

CHANGELOG.md
package.json
src/data/translations/spanish.ts

- Update Spanish translations per mariana's suggestions

Update spanish translations

---

CHANGELOG.md
package.json
src/data/translations/spanish.ts

- Updated spanish translations

Release 3.2.1

---

.circleci/config.yml
.prettierignore
codecov.yml
package.json
yarn.lock

- add codecov, codecov.yml and circleci config
- add coverage to prettier
- https://codecov.io/gh/pxblue

initial codecov config

---

.circleci/config.yml

Fix tag package script

---

CHANGELOG.md
docs/API.md
package.json
src/contexts/AuthUIContextProvider/provider.tsx
src/contexts/AuthUIContextProvider/types.ts
src/data/translations/chinese.ts
src/data/translations/english.ts
src/data/translations/french.ts
src/data/translations/spanish.ts
src/data/translations/types.ts

Fixes PXBLUE-2255.
- Add registrationConfig prop to AuthUIContextProvider to customize the character limits for first and last name text fields.

Add registrationConfig prop to AuthUIContextProvider

---

.circleci/config.yml

Rename workflow name

---

src/index.ts

Add license

---

CHANGELOG.md
package.json

Prep 3.5.0 release (update changelog and package version)

---

.circleci/config.yml
.eslintrc.js
CHANGELOG.md
README.md
docs/API.md
package.json
yarn.lock

Fixes PXBLUE-2522 .
Update following:

Rebrand BLUI

---

package.json
src/index.ts

- Add missing export, publish another beta

Add missing export

---

CHANGELOG.md
package.json
src/contexts/AccountUIContext/actions.ts
src/contexts/RegistrationUIContext/actions.ts

Fixes PXBLUE-2518.
- Fix typing errors

Fix typing errors

---

package.json

- Version number v3.6.0-beta.2 -> v3.6.0

Ready to publish v3.6.0

---

package.json

Fixes # .
- add keyword section with keywords in package.json for view on NPM
- 
- 
-

add keywords

---

CHANGELOG.md
package.json
src/data/translations/portuguese.ts

Fixes #59 
- Fix bold text on Forgot Password page while using Portuguese translations.

Fix bold text

---

CHANGELOG.md
package.json
src/contexts/AuthUIContextProvider/provider.tsx
src/contexts/AuthUIContextProvider/types.ts
src/contexts/RegistrationUIContext/actions.ts
src/contexts/SecurityContextProvider/SecurityContextProvider.tsx
src/stores/AuthUIInternalStore.tsx
yarn.lock

- Update to support React 18
- This can be tested in the `feature/upgrade-to-react-18` branch in the react-workflows repo. There is a `react-auth-shared` beta package published as 3.0.2-beta.0.

Support React 18

---

CHANGELOG.md
docs/API.md
package.json
src/contexts/AuthUIContextProvider/provider.tsx
src/contexts/AuthUIContextProvider/types.ts
src/contexts/RegistrationUIContext/actions.ts

Fixes BLUI-3097.
- Add `disablePagerAnimation` prop to `AuthUIContextProvider` to disable pager animations.

Add disablePagerAnimation prop

---

docs/API.md

- Add RN only note to disablePagerAnimation doc entry

Add RN only note to disablePagerAnimation doc entry

---

CHANGELOG.md
package.json
src/types/AccountDetails.tsx

Part of https://github.com/brightlayer-ui/react-native-workflows/issues/73

BLUI-2966 fix keyboard next button with refs

---

CHANGELOG.md
package.json

Prepare to release v3.7.2

---

CHANGELOG.md
package.json

Prepare to publish v3.7.3

---

docs/API.md

Fixes BLUI-3644 & #46.
- Update logicErrorDisplayConfig docs

Update logicErrorDisplayConfig docs

---

.circleci/config.yml
README.md
package.json
yarn.lock

Fixes BLUI-3627 .
- use latest codecov and prep report
- remove old codecov dependency
- re-activate report
- fix
-
-

use latest codecov & update badge link

---

CHANGELOG.md
package.json

- update change log and package version
-
-
-
-
-

Prepare release 3.8.0
